config/routes.rb
Quotastk::Application.routes.draw do

  
  
  resources :quotes
  
  
  resources :speakers do
    get 'quotes', :on => :member
  end

  
  root :to => "quotes#index"

end

app/models/channel.rb
class Channel < ActiveRecord::Base
  belongs_to :network
end

app/models/network.rb
class Network < ActiveRecord::Base
  has_many :channels
end

app/models/quote.rb
class Quote < ActiveRecord::Base
  has_and_belongs_to_many :speakers, :order => "name ASC"
  accepts_nested_attributes_for :speakers
  
  scope :normal, where(:offensive => false)
  scope :offensive, where(:offensive => true)
  scope :spam, where(:spam => true)
  
  validates_presence_of :body, :on => :create, :message => "can't be blank"
  
  # class methods
  def self.find_all_by_speaker_name(speaker_name)
    Speaker.find_by_name(speaker_name).quotes
  end
  
  # instance methods
  def speaker_list
    speakers.collect{ |speaker| speaker.name }.to_sentence
  end
end

app/models/speaker.rb
class Speaker < ActiveRecord::Base
  has_and_belongs_to_many :quotes
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/quotes_controller.rb
class QuotesController < ApplicationController
  def index
    @quotes = Quote.normal
  end
  
  def new
    @quote = Quote.new
    @quote.speakers.build
  end
  
  def create
    unsentencize_speaker_names
    @quote = Quote.create params[:quote]
    redirect_to quotes_path
  end

private
  
  def unsentenceize_speaker_names
    speaker_names = params[:quote][:speakers_attributes]['0'][:name].sentence_to_array
    speaker_names.each_with_index do |speaker_name, i|
      params[:quote][:speakers_attributes]['0'][:name] = speaker_name if i==0
      params[:quote][:speakers_attributes].store("#{i}", {:name => speaker_name})
      if (speaker = Speaker.find_by_name(speaker_name))
        params[:quote][:speakers_attributes]["#{i}"].store(:id, speaker.id)
      end
    end
  end
  
end

app/controllers/speakers_controller.rb
class SpeakersController < ApplicationController
  def quotes
    @speaker = Speaker.find(params[:id])
  end  
end

app/helpers/application_helper.rb
module ApplicationHelper
  def site_title
    'Quotastk'
  end
  
end

app/helpers/quotes_helper.rb
module QuotesHelper
  def offensive_link(quote)
    if quote.offensive
      link_text = 'Not offensive'
    else
      link_text = 'Offensive'
    end
    link_to link_text, '#'
  end
  
  def spam_link(quote)
    if quote.offensive
      link_text = 'Not spam'
    else
      link_text = 'Spam'
    end
    link_to link_text, '#'
  end
  
  def speakers_list(quote)
    links = quote.speakers.collect do |speaker| 
      link_to speaker.name, quotes_speaker_url(speaker)
    end 
    return links.to_sentence.html_safe
  end
end

app/helpers/speakers_helper.rb
module SpeakersHelper
end

app/views/layouts/_quick_settings.html.erb
<p><%= check_box_tag :offensive %><%= label_tag :offensive, "Show offensive quotes" %><br/>
   <%= check_box_tag :spam %><%= label_tag :spam, "Show quotes marked as spam" %>
</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= site_title %></title>
    <%= stylesheet_link_tag :all %>
    <%= javascript_include_tag :defaults %>
    <%= csrf_meta_tag %>
  </head>
  <body id="top">
    <div id="page">
      <div id="header">
        <h1 id="quotastk">Quotastk</h1>
      </div>
      <div id="body">
        <div id="primary">
          <%= yield %>
        </div>
        <div id="secondary">
          <%= yield(:secondary) %>
        </div>
      </div>
      <div id="footer">
      </div>
    </div>
  </body>
</html>

app/views/quotes/_form.html.erb
<%= form_for @quote do |f| -%>
<div class="field">
  <%= f.label :body, "Quote" %><br/>
  <%= f.text_area :body, :cols => 80, :rows => 10 %>
</div>

<div class="field">
<%= f.fields_for :speakers do |s| -%>
  <%= s.label :name, "Speaker(s)" %><br/>
  <div class="instructions">(Use a comma delimited list of names)</div>
  <%= s.text_field :name %>
<% end -%>
</div>

<div class="field">
  <%= f.label :context %><br/>
  <%= f.text_field :context %>
</div>

<div class="field">
  <%= check_box_tag 'from-irc', 'from_irc', false, :onchange => 'ircToggle()' %><%= label_tag 'from-irc', "This quote is from IRC" %>
  <div id="irc-toggle">
    <%= f.fields_for :channel do |c| %>
      <div class="sub field">
        <%= c.label :name, "Channel" %><br/>
        <%= c.text_field :name %>
      </div>
      <div class="sub field">
        <%= c.fields_for :network do |n| %>
          <%= n.label :name, "Network" %><br/>
          <%= n.text_field :name %>
        <% end %>
      </div>
    <% end %>
  </div>
</div>

<div class="field sumbit">
  <%= f.submit %>
  or <%= link_to "Cancel", :back %>
</div>
<% end -%>

app/views/quotes/_quote.html.erb
<div class="quote">
  <div class="body"><%= quote.body %></div>
  <div class="attribution"><span class="speakers">&mdash;<%= speakers_list(quote) %></span>,
  <span class="context"><%= quote.context %></span></div>
  <div class="date"><%= time_ago_in_words quote.date %> ago</div>
  <div class="flag actions">
    <%= offensive_link(quote) %> <%= spam_link(quote) %>
  </div>
</div>

app/views/quotes/index.html.erb
<% @quotes.each do |quote| %>
  <%= render :partial => 'quote', :locals => { :quote => quote } %>
<% end %>

<%= link_to "Back to top", :anchor => "top" %>

<% content_for :secondary do -%>
  <p><%= link_to "Submit quote", new_quote_url %></p>
  <%= render :partial => 'layouts/quick_settings' %>
<% end -%>

app/views/quotes/new.html.erb
<% form_for @quote do |f| %>
<div class="field">
  <%= f.label :body, "Quote" %>
  <%= f.text_area :body %>
</div>

<div class="field sumbit">
  <%= f.submit %>
</div>
<% end %>

app/views/speakers/quotes.html.erb
<h2><%= @speaker.name %>'s Quotes</h2>
<% @speaker.quotes.each do |quote| %>
  <%= render :partial => 'quotes/quote', :locals => { :quote => quote } %>
<% end %>
<%= link_to "Back to the Quote List", :root %>